# Standard properties
# -------------------

logging.file.path: C:/AppData_Java17/JobVacanciesApp/log-files
logging.file.name: C:/AppData_Java17/JobVacanciesApp/log-files/jobVacanciesApp.log
logging.logback.rollingpolicy.file-name-pattern: C:/AppData_Java17/JobVacanciesApp/log-files/jobVacanciesApp.%d{yyyy-MM-dd}.%i.log

# Ad-hoc properties
# -----------------

jobvacanciesapp.authUserCurriculumFilesPath: C:/AppData_Java17/JobVacanciesApp/auth-user-curriculum-files/
jobvacanciesapp.authUserEntityQueryFilesPath: C:/AppData_Java17/JobVacanciesApp/auth-user-entity-query-files/
jobvacanciesapp.jobCompanyLogosPath: C:/AppData_Java17/JobVacanciesApp/job-company-logos/
